In [3]:
import numpy as np

In [4]:
a1 = np.array([1, 2, 3, 4, 5])

#배열 개수 , 모양
a1.shape


(5,)

In [5]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                [[1,2,3],[4,5,6],[7,8,9]],
                [[1,2,3],[4,5,6],[7,8,9]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [7]:
# 모든 요소를 0으로 초기화
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
# 모든 요소를 1로 초기화
#np.ones(3)
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# 모든 요소를 지정한 값으로 초기화
np.full((3, 3), 1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

In [10]:
# 단위행렬(identity matrix) 생성
# - 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# 삼각행렬 생성
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [12]:
# 초기화되지 않은 배열 생성
# - 초기화가 없어서 배열 생성비용 저렴하고 빠름
# - 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음
np.empty(5)

array([1.01830046e-311, 6.95187041e-310, 4.40706556e-321, 6.95187124e-310,
       4.00540456e-307])

In [13]:
# 지정된 배열과 shape가 같은 행렬 생성
# np.zeros_like()
# np.ones_like()
# np.full_like()
# np.empty_like()
print(a1)
np.zeros_like(a1)


[1 2 3 4 5]


array([0, 0, 0, 0, 0])

In [14]:
np.full_like(a1, 10)

array([10, 10, 10, 10, 10])

In [15]:
# 정수 범위로 배열 생성
np.arange(0, 30, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [16]:
# 범위 내에서 균든 간격의 배열 생성
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
# 범위 내에서 균등간격으로 로그 스케일로 배열 생성
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [18]:
# 랜덤한 수의 배열 생성
np.random.random((3,3))

array([[0.71267204, 0.3439401 , 0.89739877],
       [0.55729676, 0.95657879, 0.74845609],
       [0.29119877, 0.67084131, 0.74662864]])

In [19]:
# 일정 구간의 랜덤 정수의 배열 생성
np.random.randint(0, 10, (3, 3))

array([[6, 7, 7],
       [6, 9, 3],
       [8, 5, 9]])

In [20]:
# np.random.normal() : 정규분포 ( normal distribution ) 를 고려한 랜덤한 수의 배열생성
# 평균 = 0, 표준편차= 1,3x3 배열
np.random.normal(0, 1, (3, 3))

array([[-1.40537674, -0.23843273, -0.3312692 ],
       [-0.07293439, -1.46836036,  2.20872106],
       [-1.82175416, -1.63848559,  0.08134819]])

In [21]:
# random.rand() : 균등분포 (uniform distribution )를 고려한 랜덤한 수의 배열 생성
np.random.rand(3,3)

array([[0.10911929, 0.56642221, 0.30282874],
       [0.22895816, 0.6111397 , 0.97300892],
       [0.63035154, 0.29742571, 0.71588296]])

In [22]:
# random.randn() : 표준 정규 분포 ( standard normal distribution ) 를 고려한 랜덤한 수의 배열 생성
np.random.randn(3,3)

array([[ 0.22564695,  1.02023687,  0.05042227],
       [ 0.52555043, -0.39847479, -0.92167598],
       [-0.37521456, -0.09891383, -0.23266974]])

In [23]:
# dtype : 타입
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [25]:
np.full((3,3),1, dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
# 날짜 시간
date = np.array('2020-01-01', dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [27]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [28]:
datetime = np.datetime64('2020-10-20 12:00')
datetime

numpy.datetime64('2020-10-20T12:00')

In [29]:
datetime = np.datetime64('2020-10-20 12:00:12.34', 'ns')
datetime

numpy.datetime64('2020-10-20T12:00:12.340000000')

배열 값 삽입/수정/삭제/복사

In [30]:
print(a1)
b1 = np.insert(a1, 0, 10)
print(b1)
c1 = np.insert(a1, 2, 10)
print(c1)

[1 2 3 4 5]
[10  1  2  3  4  5]
[ 1  2 10  3  4  5]


In [31]:
print(a1)
a1[0] = 3
a1[1] = 2
a1[2] = 1
print(a1)
a1[:3] = 1,2,3  

[1 2 3 4 5]
[3 2 1 4 5]


In [32]:
# copy() 배열이나 하위 배열 내의 값을 명시적으로 복사

In [33]:
#배열변환

#배열 전치 및 축 변경


print(a3.T)

[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [34]:
print(a2)
print(a2.swapaxes(1, 0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [35]:
#배열의 형상을 변경
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
# 새로운 축 추가
print(n1)
print(n1[np.newaxis, :5])
print(n1[:5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [37]:
# 배열 모양만 변경
n2 = np.random.randint(0, 10, (2, 5))
print(n2)
n2.resize(5, 2)
print(n2)

[[2 1 2 0 0]
 [5 2 1 6 9]]
[[2 1]
 [2 0]
 [0 5]
 [2 1]
 [6 9]]


In [38]:
# 배열 크기 증가
# 남은 공간은 0으로 채워짐
n2.resize((5, 5))
n2

array([[2, 1, 2, 0, 0],
       [5, 2, 1, 6, 9],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [39]:
# 배열 크기 감소
# 포함되지 않은 값은 삭제
n2.resize((3, 3),refcheck=False)
print(n2)

[[2 1 2]
 [0 0 5]
 [2 1 6]]


In [40]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)
b2 = np.arange(10, 19).reshape(3,3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [41]:
# axis 지정이 없으면 1차원 배열 형태로 변형되어 결합
c2 = np.append(a2, b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [42]:
# axis 를 0 로 지정
# shape[0]을 제외한 나머지 shape는 갈아야함
c2 = np.append(a2, b2, axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [43]:
# axis 를 1 로 지정
# shape[1]을 제외한 나머지 shape는 갈아야함
c2 = np.append(a2, b2, axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [44]:
# 배열 연결

# 튜플이나 배열의 리스트를 인수로 사용해 배열 연결
a1 = np.array([1, 3, 5])
b1 = np.array([2, 4, 6])
np.concatenate([a1, b1])

array([1, 3, 5, 2, 4, 6])

In [45]:
c1 = np.array([7, 8 ,9])
np.concatenate([a1, b1, c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [46]:
a2 = np.array([[1, 2, 3],
                [4, 5, 6]])
np.concatenate([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [47]:
a2 = np.array([[1, 2, 3],
                [4, 5, 6]])
np.concatenate([a2, a2], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [48]:
# 수직 스택(vertical stack), 1차원으로 연결
np.vstack([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [49]:
# 수평 스택(horizontal stack), 2차원으로 연결
np.hstack([a2, a2])


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [50]:
# 길이 스택(depth stack), 3차원으로 연결
np.dstack([a2,a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

In [51]:
# 새로운 차원으로 연결
np.stack([a2, a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [52]:
# 배열 분할
a1 = np.arange(0,10)
print(a1)
b1, c1 = np.split(a1, [5])
print(b1, c1)
b1, c1, d1, e1, f1 = np.split(a1, [2, 4, 6, 8])
print(b1, c1, d1, e1, f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


In [53]:
# 수직 분할, 1차원으로 분할
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.vsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


In [54]:
# 수평 분할, 2차원으로 분할
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.hsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


In [55]:
# 깊이 분할, 3차원으로 분할
a3 = np.arange(1, 28).reshape(3, 3, 3)
print(a3)
b3, c3 = np.hsplit(a3, [2])
print(b3)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [13 14 15]]

 [[19 20 21]
  [22 23 24]]]
[[[ 7  8  9]]

 [[16 17 18]]

 [[25 26 27]]]


In [56]:
# 브로드 캐스팅 ( Broadcasting )

In [57]:
a1 = np.array([1, 2, 3])
print(a1)
print(a1 + 5)

a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print(a1 + a2)

b2 = np.array([1, 2, 3]).reshape(3, 1)
print(b2)
print(a1 + b2)

[1 2 3]
[6 7 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [58]:
# 산술연산
a1 = np.arange(1, 10)
print(a1)
print(a1 + 1)
print(np.add(a1, 10))
print(a1 - 2 )
print(np.subtract(a1, 10))
print(-a1)
print(np.negative(a1))
print(a1 * 2)
print(np.multiply(a1, 2))
print(a1 / 2)
print(np.divide(a1 , 2))
print(a1 // 2)
print(np.floor_divide(a1, 2))
print(a1 ** 2)
print(np.power(a1, 2))
print(a1 % 2)
print(np.mod(a1, 2))

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]
[-1  0  1  2  3  4  5  6  7]
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]


In [59]:
a1 = np.arange(1, 10)
print(a1)
b1 = np.random.randint(1, 10, size=9)
print(b1)
print(a1 + b1)
print(a1 - b1)
print(a1 * b1)
print(a1 / b1)
print(a1 // b1)
print(a1 ** b1)
print(a1 % b1)


[1 2 3 4 5 6 7 8 9]
[7 8 7 6 3 1 3 7 5]
[ 8 10 10 10  8  7 10 15 14]
[-6 -6 -4 -2  2  5  4  1  4]
[ 7 16 21 24 15  6 21 56 45]
[0.14285714 0.25       0.42857143 0.66666667 1.66666667 6.
 2.33333333 1.14285714 1.8       ]
[0 0 0 0 1 6 2 1 1]
[      1     256    2187    4096     125       6     343 2097152   59049]
[1 2 3 4 2 0 1 1 4]


In [60]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2 = np.random.randint(1, 10, size=(3, 3))
print(b2)
print(a2 + b2)
print(a2 - b2)
print(a2 * b2)
print(a2 / b2)
print(a2 // b2)
print(a2 ** b2)
print(a2 % b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 2 1]
 [7 4 9]
 [9 4 8]]
[[ 4  4  4]
 [11  9 15]
 [16 12 17]]
[[-2  0  2]
 [-3  1 -3]
 [-2  4  1]]
[[ 3  4  3]
 [28 20 54]
 [63 32 72]]
[[0.33333333 1.         3.        ]
 [0.57142857 1.25       0.66666667]
 [0.77777778 2.         1.125     ]]
[[0 1 3]
 [0 1 0]
 [0 2 1]]
[[       1        4        3]
 [   16384      625 10077696]
 [40353607     4096 43046721]]
[[1 0 0]
 [4 1 6]
 [7 0 1]]


In [61]:
# 절대값 함수 ( Absolute Function )

# 내장된 절대값 함수
a1 = np.random.randint(-10, 10, size=5)
print(a1)
print(np.absolute(a1))
print(np.abs(a1))

[-8 -4  7  8  8]
[8 4 7 8 8]
[8 4 7 8 8]


In [62]:
# 제곱 제곱근 함수
print(a1)
print(np.square(a1))
print(np.sqrt(a1))

[-8 -4  7  8  8]
[64 16 49 64 64]
[       nan        nan 2.64575131 2.82842712 2.82842712]


C:\Users\dxsystem\AppData\Local\Temp\ipykernel_19008\3478212206.py:4: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(a1))


In [64]:
# 지수와 로그 함수 ( Exponential and Log Function )
a1 = np.random.randint(1, 10, size=5)
print(a1)
print(np.exp(a1)) 
print(np.exp2(a1)) 
print(np.power(a1, 2))

[1 4 9 4 3]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 5.45981500e+01
 2.00855369e+01]
[  2.  16. 512.  16.   8.]
[ 1 16 81 16  9]


In [65]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[1 4 9 4 3]
[0.         1.38629436 2.19722458 1.38629436 1.09861229]
[0.        2.        3.169925  2.        1.5849625]
[0.         0.60205999 0.95424251 0.60205999 0.47712125]


In [66]:
# 삼각함수

t = np.linspace(0, np.pi, 3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [67]:
x = [-1, 0, 1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


In [69]:
# 집계함수
 
# 합 계산
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(a2.sum(), np.sum(a2))
print(a2.sum(axis=0), np.sum(a2, axis=0))
print(a2.sum(axis=1), np.sum(a2, axis=1))

[[1 9 7]
 [8 7 3]
 [2 9 8]]
54 54
[11 25 18] [11 25 18]
[17 18 19] [17 18 19]


In [70]:
# 누적합 계산
print(a2)
print(np.cumsum(a2))
print(np.cumsum(a2, axis=0))
print(np.cumsum(a2, axis=1))

[[1 9 7]
 [8 7 3]
 [2 9 8]]
[ 1 10 17 25 32 35 37 46 54]
[[ 1  9  7]
 [ 9 16 10]
 [11 25 18]]
[[ 1 10 17]
 [ 8 15 18]
 [ 2 11 19]]


In [71]:
# 차분 계산
print(a2)
print(np.diff(a2))
print(np.diff(a2, axis=0))
print(np.diff(a2, axis=1))

[[1 9 7]
 [8 7 3]
 [2 9 8]]
[[ 8 -2]
 [-1 -4]
 [ 7 -1]]
[[ 7 -2 -4]
 [-6  2  5]]
[[ 8 -2]
 [-1 -4]
 [ 7 -1]]


In [72]:
# 곱 계산
print(a2)
print(np.prod(a2))
print(np.prod(a2, axis=0))
print(np.prod(a2, axis=1))

[[1 9 7]
 [8 7 3]
 [2 9 8]]
1524096
[ 16 567 168]
[ 63 168 144]


In [73]:
# 누적곱 계산
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2, axis=0))
print(np.cumprod(a2, axis=1))

[[1 9 7]
 [8 7 3]
 [2 9 8]]
[      1       9      63     504    3528   10584   21168  190512 1524096]
[[  1   9   7]
 [  8  63  21]
 [ 16 567 168]]
[[  1   9  63]
 [  8  56 168]
 [  2  18 144]]


In [74]:
# 점곱 / 행렬곱 계산
print(a2)
b2 = np.ones_like(a2)
print(b2)
print(np.dot(a2, b2))
print(np.matmul(a2, b2))

[[1 9 7]
 [8 7 3]
 [2 9 8]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[17 17 17]
 [18 18 18]
 [19 19 19]]
[[17 17 17]
 [18 18 18]
 [19 19 19]]


In [75]:
# 텐서곱 계산
print(a2)
print(b2)
print(np.tensordot(a2, b2))
print(np.tensordot(a2, b2, axes=0))
print(np.tensordot(a2, b2, axes=1))

[[1 9 7]
 [8 7 3]
 [2 9 8]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
54
[[[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[9 9 9]
   [9 9 9]
   [9 9 9]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]]


 [[[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]]


 [[[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[9 9 9]
   [9 9 9]
   [9 9 9]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]]]
[[17 17 17]
 [18 18 18]
 [19 19 19]]


In [78]:
# 벡터곱
x = [1, 2, 3]
y = [4, 5, 6]
print(np.cross(x, y))

[-3  6 -3]
