In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [4]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

tf.model = tf.keras.Sequential()

tf.model.add(tf.keras.layers.Dense(units=1, input_dim=3))  # input_dim=3 gives multi-variable regression
tf.model.add(tf.keras.layers.Activation('linear'))  # this line can be omitted, as linear activation is default

tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
tf.model.summary()
history = tf.model.fit(x_data, y_data, epochs=100)

y_predict = tf.model.predict(np.array([[72., 93., 90.]]))
print(y_predict)

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 1)                 4         
_________________________________________________________________
activation_2 (Activation)    (None, 1)                 0         
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
1/1 [==============================] - 0s 192ms/step - loss: 19217.6504
Epoch 2/100
1/1 [==============================] - 0s 3ms/step - loss: 6028.0972
Epoch 3/100
1/1 [==============================] - 0s 3ms/step - loss: 1893.8723
Epoch 4/100
1/1 [==============================] - 0s 4ms/step - loss: 598.0087
Epoch 5/100
1/1 [==============================] - 0s 8ms/step - loss: 191.8222
Epoch 6/100
1/1 [==============================] - 0s 3ms/step - loss: 64.5023
Epoch 7/100
1/1 [====================

In [5]:
xy = np.loadtxt('./data/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

# data output
'''
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 ...
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 ...
 [149.]
 [192.]] 
y_data shape: (25, 1)
'''
tf.model = tf.keras.Sequential()
# activation function doesn't have to be added as a separate layer. Add it as an argument of Dense() layer
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=3, activation='linear'))
# tf.model.add(tf.keras.layers.Activation('linear'))
tf.model.summary()

tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
history = tf.model.fit(x_data, y_data, epochs=2000)

# Ask my score
print("Your score will be ", tf.model.predict([[100, 70, 101]]))
print("Other scores will be ", tf.model.predict([[60, 70, 110], [90, 100, 80]]))

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)
Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 1)                 4         
Total params: 4
Trainable params: 4
Non-trainable params: 0
______________________

c:\Users\dxsystem\.conda\envs\tensor\lib\site-packages\keras\optimizer_v2\optimizer_v2.py:355: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


1/1 [==============================] - 0s 209ms/step - loss: 3426.9785
Epoch 2/2000
1/1 [==============================] - 0s 9ms/step - loss: 1271.9445
Epoch 3/2000
1/1 [==============================] - 0s 10ms/step - loss: 475.1683
Epoch 4/2000
1/1 [==============================] - 0s 4ms/step - loss: 180.5776
Epoch 5/2000
1/1 [==============================] - 0s 4ms/step - loss: 71.6586
Epoch 6/2000
1/1 [==============================] - 0s 8ms/step - loss: 31.3876
Epoch 7/2000
1/1 [==============================] - 0s 12ms/step - loss: 16.4979
Epoch 8/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.9922
Epoch 9/2000
1/1 [==============================] - 0s 13ms/step - loss: 8.9560
Epoch 10/2000
1/1 [==============================] - 0s 12ms/step - loss: 8.2027
Epoch 11/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.9236
Epoch 12/2000
1/1 [==============================] - 0s 4ms/step - loss: 7.8199
Epoch 13/2000
1/1 [=======================